// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'task_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5821547428411220278),
      name: 'TaskEntity',
      lastPropertyId: const obx_int.IdUid(9, 6785539543551506521),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7082572088507706036),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2173642786486121302),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 8889622069513287372)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7990987261647642290),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2174191268454943514),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6299086952117280512),
            name: 'isCompleted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 902155289598578036),
            name: 'isArchived',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8500437612472358801),
            name: 'dateCreated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2464328590272633292),
            name: 'updateDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6785539543551506521),
            name: 'isSync',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5821547428411220278),
      lastIndexId: const obx_int.IdUid(1, 8889622069513287372),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    TaskEntity: obx_int.EntityDefinition<TaskEntity>(
        model: _entities[0],
        toOneRelations: (TaskEntity object) => [],
        toManyRelations: (TaskEntity object) => {},
        getId: (TaskEntity object) => object.id,
        setId: (TaskEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TaskEntity object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addBool(4, object.isCompleted);
          fbb.addBool(5, object.isArchived);
          fbb.addInt64(6, object.dateCreated.millisecondsSinceEpoch);
          fbb.addInt64(7, object.updateDate.millisecondsSinceEpoch);
          fbb.addBool(8, object.isSync);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final isCompletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final isArchivedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final isSyncParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final dateCreatedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final updateDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final object = TaskEntity(
              uid: uidParam,
              title: titleParam,
              description: descriptionParam,
              isCompleted: isCompletedParam,
              isArchived: isArchivedParam,
              isSync: isSyncParam,
              dateCreated: dateCreatedParam,
              updateDate: updateDateParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TaskEntity] entity fields to define ObjectBox queries.
class TaskEntity_ {
  /// See [TaskEntity.id].
  static final id =
      obx.QueryIntegerProperty<TaskEntity>(_entities[0].properties[0]);

  /// See [TaskEntity.uid].
  static final uid =
      obx.QueryStringProperty<TaskEntity>(_entities[0].properties[1]);

  /// See [TaskEntity.title].
  static final title =
      obx.QueryStringProperty<TaskEntity>(_entities[0].properties[2]);

  /// See [TaskEntity.description].
  static final description =
      obx.QueryStringProperty<TaskEntity>(_entities[0].properties[3]);

  /// See [TaskEntity.isCompleted].
  static final isCompleted =
      obx.QueryBooleanProperty<TaskEntity>(_entities[0].properties[4]);

  /// See [TaskEntity.isArchived].
  static final isArchived =
      obx.QueryBooleanProperty<TaskEntity>(_entities[0].properties[5]);

  /// See [TaskEntity.dateCreated].
  static final dateCreated =
      obx.QueryDateProperty<TaskEntity>(_entities[0].properties[6]);

  /// See [TaskEntity.updateDate].
  static final updateDate =
      obx.QueryDateProperty<TaskEntity>(_entities[0].properties[7]);

  /// See [TaskEntity.isSync].
  static final isSync =
      obx.QueryBooleanProperty<TaskEntity>(_entities[0].properties[8]);
}
